[project]
name = "names-art"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rrozen", email = "robirozen@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyfiglet>=1.0.4",
]

[project.scripts]
names-art = "names_art:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
